# listen to events --> on --> type of event
name: wk_1
# parallel actions
on: 
  push:
  workflow-dispatch:

jobs:
  J01:
  # vm -- container -- expired in 10 mins
    runs-on:   ubuntu-latest
    steps:

      -name: checkout
        uses: actions/checkout@v4.1.7
        
      -name: Welcome
        run: echo "Welcome to your first action"


      -name: sc
        run:
          |
          chmod +x script.sh
          script.sh


      # -name: install cowsay program
      #   run: sudo apt-get install cowsay -y
